### ISSUE TITLE
"Contributor" misspelled as "Contributer" in multiple places.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/manifest.json#3]
The v1 manifest docs spell "contributor" incorrectly as "contributer" in multiple spots.

https://github.com/blish-hud/manifest.json/blob/master/manifest-v1.md

**Comment by blog-a1** [comment]
Requesting to get assigned.

**Comment by simonamor** [comment]
Does the merged PR mean this issue is resolved?
